#!/bin/sh
#/usr/local/bin/
/home/itsmeit/Downloads/itsmeitsrcbackup

chown root.root /var/backup/files* -R
find /var/backup/files* -type f -exec chmod 400 {} \;
find /var/backup/files* -type d -exec chmod 700 {} \;
